apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.list_cart, name='list_cart'),
    path('add_to_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('excluir/<int:product_id>/', views.delete_cartitem, name='delete_cartitem'),
    path('cart/decrease_quantity/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/increase_quantity/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
]

apps/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.list_products, name='list_products'),
    path('adicionar/', views.add_product, name='add_product'),
    path('editar/<int:id_product>/', views.edit_product, name='edit_product'),
    path('excluir/<int:id_product>/', views.delete_product, name='delete_product'),
]

marketapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos_itens/', include('orders.urls', namespace='orders_items')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('hortifruti/', include('hortifruti.urls')),
    path('bebidas/', include('bebidas.urls')),
    path('bomboniere/', include('bomboniere.urls')),
    path('suplementos/', include('suplementos.urls')),
    path('padaria/', include('padaria.urls')),
]

apps/products/models.py
from django.db import models
from categories.models import Category

# Create your models here.

class Product(models.Model):
    name = models.CharField('Nome', max_length=50)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    date_fabrication = models.DateField('Data Fabricacao', auto_now=False, auto_now_add=False)
    is_active = models.BooleanField('Ativo', default=False)
    quantity = models.IntegerField(null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering =['id']

    def __str__(self):
        return self.name

apps/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ()

apps/products/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from .forms import ProductForm
from .models import Product

# Create your views here.

def add_product(request):
    template_name = 'products/add_product.html'
    context = {}
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('products:list_products')
    form = ProductForm()
    context['form'] = form
    return render(request, template_name, context)

def list_products(request):
    template_name = 'products/list_products.html'
    products = Product.objects.filter()
    context = {
        'products': products
    }
    return render(request, template_name, context)

def edit_product(request, id_product):
    template_name = 'products/add_product.html'
    context ={}
    product = get_object_or_404(Product, id=id_product)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES,  instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:list_products')
    form = ProductForm(instance=product)
    context['form'] = form
    return render(request, template_name, context)

def delete_product(request, id_product):
    product = Product.objects.get(id=id_product)
    product.delete()
    return redirect('products:list_products')

templates/products/add_product.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Produto - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Produto</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.category.id_for_label }}">Categoria</label>
                    {{ form.category|add_class:"form-control" }}
                </div>
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.preco.id_for_label }}">Preço</label>
                    {{ form.preco|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.date_fabrication.id_for_label }}">Data de validade</label>
                    {{ form.date_fabrication|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.is_active.id_for_label }}">Ativar</label>
                    {{ form.is_active }}
                </div>
                <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                    {{ form.quantity|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/products/list_products.html
{% extends 'base.html' %}

{% block title %}

    Lista de Produtos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Produtos</b></h5>
        <br />
            <a href="{% url 'products:add_product' %}">Cadastro de novo produto</a>
        <br />
        <br />
        <div class="row">
            <div class ="col-md-12">
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">id</th>
                    <th scope="col">NOME</th>
                    <th scope="col">PREÇO</th>
                    <th scope="col">VALIDADE</th>
                    <th scope="col">EM ESTOQUE</th>
                    <th scope="col">CATEGORIA</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr>
                            <th scope="row">{{ product.id }}</th>
                            <td>{{ product.name }}</td>
                            <td>{{ product.preco }}</td>
                            <td>{{ product.date_fabrication }}</td>
                            <td>
                                {% if product.is_active == True %}
                                    Disponível
                                {% endif %}
                                {% if product.is_active == False %}
                                    Indisponível
                                {% endif %}
                            </td>
                            <td>{{ product.category }}</td>
                            <td>
                                <a href="{% url 'products:edit_product' product.id %}" class="btn btn-primary btn-sm">EDITAR</a>
                            </td>
                            <td>    
                                <a href="{% url 'products:delete_product' product.id %}" class="btn btn-danger btn-sm ">EXCLUIR</a>
                            </td>
                            <td>    
                                <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-danger btn-sm" style="background-color: #006400; color: #ffffff;">CARRINHO+</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}