apps/categories/urls.py
from django.urls import path
from . import views

app_name = 'categories'

urlpatterns = [
    path('', views.list_categories, name='list_categories'),
    path('adicionar/', views.add_category, name='add_category'),
    path('editar/<int:id_category>/', views.edit_category, name='edit_category'),
    path('excluir/<int:id_category>/', views.delete_category, name='delete_category'),
]

marketapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos_itens/', include('orders.urls', namespace='orders_items')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('hortifruti/', include('hortifruti.urls')),
    path('bebidas/', include('bebidas.urls')),
    path('bomboniere/', include('bomboniere.urls')),
    path('suplementos/', include('suplementos.urls')),
    path('padaria/', include('padaria.urls')),
]

apps/categories/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField('Nome', max_length=50)
    description = models.TextField('Descricao', max_length=100) 
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering =['id']

    def __str__(self):
        return self.name
    
#class Hortifruti(Category):
#    is_organic = models.BooleanField('Orgânico', default=False)
#    peso = models.FloatField('Peso')

apps/categories/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        exclude = ()

apps/categories/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CategoryForm
from .models import Category

# Create your views here.

def add_category(request):
    template_name = 'categories/add_category.html'
    context = {}
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('categories:list_categories')
    form = CategoryForm()
    context['form'] = form
    return render(request, template_name, context)

def list_categories(request):
    template_name = 'categories/list_categories.html'
    categories = Category.objects.filter()
    context = {
        'categories': categories
    }
    return render(request, template_name, context)

def edit_category(request, id_category):
    template_name = 'categories/add_category.html'
    context ={}
    category = get_object_or_404(Category, id=id_category)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('categories:list_categories')
    form = CategoryForm(instance=category)
    context['form'] = form
    return render(request, template_name, context)

def delete_category(request, id_category):
    category = Category.objects.get(id=id_category)
    category.delete()
    return redirect('categories:list_categories')

templates/categories/add_category.html
{% extends 'base.html' %}
{% load widget_tweaks %} 

{% block title %}

    Adicionar Categoria - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Categoria</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                 </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/categories/list_categories.html
{% extends 'base.html' %}

{% block title %}

    Lista de Categorias - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Categorias</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'categories:add_category' %}">Cadastro de nova categoria</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">id</th>
                    <th scope="col">NOME</th>
                    <th scope="col">DESCRIÇÃO</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                        <tr>
                            <th scope="row">{{ category.id }}</th>
                            <td>{{ category.name }}</td>
                            <td>{{ category.description }}</td>
                            <td>
                                <a href="{% url 'categories:edit_category' category.id %}" class="btn btn-primary btn-sm">EDITAR</a>
                            </td>
                            <td>
                                <a href="{% url 'categories:delete_category' category.id %}" class="btn btn-danger btn-sm ">EXCLUIR</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}